### ISSUE TITLE
Fable compilation failed

### ISSUE THREAD

**Issue by AlbertoLeon** [Zaid-Ajaj/Feliz#533] opened 2022-12-18 13:10 UTC
I really don't now how to progress from here
I followed the steps from https://shmew.github.io/Feliz.MaterialUI/#usage/installation

```
Fable compilation finished in 956ms

.\src\Extensions.fs(5,6): (5,11) error FSHARP: The namespace or module 'Fable' is not defined. (code 39)
.\src\Extensions.fs(6,6): (6,11) error FSHARP: The namespace or module 'Fable' is not defined. (code 39)
.\src\Extensions.fs(12,49): (12,62) error FSHARP: The value or constructor 'importDefault' is not defined. (code 39)
.\src\Extensions.fs(18,7): (18,11) error FSHARP: The type 'Emit' is not defined. (code 39)
.\src\Extensions.fs(19,43): (19,51) error FSHARP: The value or constructor 'jsNative' is not defined. (code 39)
.\src\Extensions.fs(34,11): (34,15) error FSHARP: The type 'Emit' is not defined. (code 39)
.\src\Extensions.fs(38,38): (38,51) error FSHARP: The value or constructor 'importDefault' is not defined. (code 39)
.\src\Components.fs(3,6): (3,11) error FSHARP: The namespace or module 'Feliz' is not defined. (code 39)
.\src\Components.fs(4,6): (4,11) error FSHARP: The namespace or module 'Feliz' is not defined. (code 39)
.\src\Components.fs(11,7): (11,21) error FSHARP: The type 'ReactComponent' is not defined. (code 39)
.\src\Components.fs(12,34): (12,38) error FSHARP: The value, namespace, type or module 'Html' is not defined. (code 39)
.\src\Components.fs(17,7): (17,21) error FSHARP: The type 'ReactComponent' is not defined. (code 39)
.\src\Components.fs(19,33): (19,38) error FSHARP: The value, namespace, type or module 'React' is not defined. (code 39)
.\src\Components.fs(20,9): (20,13) error FSHARP: The value, namespace, type or module 'Html' is not defined. (code 39)
.\src\Components.fs(32,7): (32,21) error FSHARP: The type 'ReactComponent' is not defined. (code 39)
.\src\Components.fs(34,39): (34,44) error FSHARP: The value, namespace, type or module 'React' is not defined. (code 39)
.\src\Components.fs(35,9): (35,14) error FSHARP: The value, namespace, type or module 'React' is not defined. (code 39)
.\src\Main.fs(3,6): (3,11) error FSHARP: The namespace or module 'Feliz' is not defined. (code 39)
.\src\Main.fs(5,6): (5,13) error FSHARP: The namespace or module 'Browser' is not defined. (code 39)
.\src\Main.fs(6,6): (6,11) error FSHARP: The namespace or module 'Fable' is not defined. (code 39)
.\src\Main.fs(8,1): (8,18) error FSHARP: The value or constructor 'importSideEffects' is not defined. (code 39)
.\src\Main.fs(10,1): (10,9) error FSHARP: The value, namespace, type or module 'ReactDOM' is not defined. (code 39)
```

**Comment by MangelMaxime** [comment] 2022-12-18 14:25
Hello @AlbertoLeon,

you are probably using .NET 7 which is causing trouble to Fable 3 right now.

Please have a look at https://github.com/fable-compiler/Fable/issues/3294 for a workaround solution.

**Comment by Zaid-Ajaj** [comment] 2022-12-25 04:20
Duplicate of https://github.com/fable-compiler/Fable/issues/3294

**Closed by Zaid-Ajaj** 2022-12-25 04:20 UTC
